version: '2.1'

services:
  
  # ------------------------------------------------------------------------------------
  # Redis Stack
  # ------------------------------------------------------------------------------------
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001"
      - "6379:6379"
    volumes:
      - local-data:/data
    privileged: true
  
  
volumes:
  local-data:
